# Generated by Django 5.1.3 on 2025-12-27 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content_at',
            new_name='created_at',
        ),
    ]
